import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SidebarLeft from "@/components/SidebarLeft";
import Feed from "@/components/Feed";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LinkedIn Clone",
  description: "Generated by create next app",
  icons: {
    icon: "/linkedin-logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}

        <Navbar />
        <div className="flex max-w-7xl mx-auto space-x-4 p-3">
          <SidebarLeft />
          <Feed />
        </div>
      </body>
    </html>
  );
}
